-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('PRET_CREATED', 'PRET_UPDATED', 'PRET_DELETED', 'VIREMENT_CREATED', 'VIREMENT_UPDATED', 'VIREMENT_DELETED', 'REMBOURSEMENT_CREATED', 'REMBOURSEMENT_UPDATED', 'REMBOURSEMENT_DELETED', 'VERSEMENT_CREATED', 'VERSEMENT_UPDATED', 'VERSEMENT_DELETED', 'CLIENT_CREATED', 'CLIENT_UPDATED', 'CLIENT_DELETED', 'CAISSIER_CREATED', 'CAISSIER_UPDATED', 'CAISSIER_DELETED', 'RETRAIT_CREATED', 'RETRAIT_UPDATED', 'RETRAIT_DELETED');

-- CreateTable
CREATE TABLE "Historique" (
    "idHistorique" TEXT NOT NULL,
    "type" "EventType" NOT NULL,
    "identifiantOfType" TEXT NOT NULL,
    "donnee" JSONB NOT NULL,
    "dateCreation" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Historique_pkey" PRIMARY KEY ("idHistorique")
);
