export enum EventType {
    PRET_CREATED = 'PRET_CREATED',
    PRET_UPDATED = 'PRET_UPDATED',
    PRET_DELETED = 'PRET_DELETED',

    REMBOURSEMENT_CREATED = 'REMBOURSEMENT_CREATED',
    REMBOURSEMENT_UPDATED = 'REMBOURSEMENT_UPDATED',
    REMBOURSEMENT_DELETED = 'REMBOURSEMENT_DELETED',

    VERSEMENT_CREATED = 'VERSEMENT_CREATED',
    VERSEMENT_UPDATED = 'VERSEMENT_UPDATED',
    VERSEMENT_DELETED = 'VERSEMENT_DELETED',

    VIREMENT_CREATED = 'VIREMENT_CREATED',
    VIREMENT_UPDATED = 'VIREMENT_UPDATED',
    VIREMENT_DELETED = 'VIREMENT_DELETED',
    
   
    CLIENT_CREATED = 'CLIENT_CREATED',
    CLIENT_UPDATED = 'CLIENT_UPDATED',
    CLIENT_DELETED = 'CLIENT_DELETED',

    CAISSIER_CREATED = 'CAISSIER_CREATED',
    CAISSIER_UPDATED = 'CAISSIER_UPDATED',
    CAISSIER_DELETED = 'CAISSIER_DELETED',
    
    RETRAIT_CREATED = 'RETRAIT_CREATED',
    RETRAIT_UPDATED = 'RETRAIT_UPDATED',
    RETRAIT_DELETED = 'RETRAIT_DELETED',
  }